name: Feature Request
description: Suggest an idea for Mystral
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What's the problem?
      description: What are you trying to do that Mystral doesn't currently support?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How do you think it should work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds you've tried, or other tools that handle this well.
